chore: update trivy version Dockerfile
aquasecurity/trivy-action pull request #96
Opened 2022-02-01 14:03 UTC by oranmoshai

2022-02-01 15:39 UTC, knqyf263 requested changes
Can you update README.md to align with the new option?
https://github.com/aquasecurity/trivy/discussions/1571

Before:

```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
```

After:

```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
```

https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning
https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-git-repo
https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-infrastucture-as-code

and here
https://github.com/aquasecurity/trivy-action#inputs

2022-02-01 15:42 UTC, knqyf263 commented
Oh, looks like we also have to fix here.
https://github.com/aquasecurity/trivy-action/blob/9c21d3ca2c14eb35419e2a8b66d1195946d579b8/entrypoint.sh#L141-L144

2022-02-01 16:10 UTC, tzurielweisberg approved these changes

2022-02-01 16:14 UTC, knqyf263 requested changes

2022-02-01 16:14 UTC, knqyf263 commented on README.md
> -| `template`       | String  |                                    | Output template (`@/contrib/sarif.tpl`, `@/contrib/gitlab.tpl`, `@/contrib/junit.tpl`)|
`template` is still valid. We just removed `sarif.tpl`.

2022-02-01 16:14 UTC, knqyf263 commented on entrypoint.sh
>  if [[ ${template} == *"sarif"* ]]; then
We have to fix this line as well.

2022-02-02 02:12 UTC, simar7 commented
> Anything else? @simar7 @krol3

lgtm, module the feedback you left!

2022-02-02 02:13 UTC, simar7 requested changes
overall lgtm, just the comments @knqyf263 mentioned.

2022-02-02 08:00 UTC, knqyf263 commented
Oran is under weather and I've updated instead. v0.23.0 contains some breaking changes. I want to make sure this update works properly. Could you test this branch? @simar7 @krol3

2022-02-02 11:54 UTC, krol3 commented
@knqyf263 , @simar7, I updated in my branch that has unit test using this latest version (0.23), It seems to work the parameters using sarif. Any feedback to improve the unit test. please take a look into in https://github.com/aquasecurity/trivy-action/pull/85

2022-02-02 19:05 UTC, knqyf263 approved these changes

2022-02-02 19:57 UTC, knqyf263 approved these changes

2022-02-02 23:19 UTC, simar7 approved these changes

2022-02-02 23:19 UTC, merged